version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    entrypoint: ""
    environment:
      MATRIX_URL: "http://tests"
      MATRIX_ID: "bot"
      MATRIX_PW: "pw"
    volumes:
      - ./:/app
