services:
  redis:
    image: redis:alpine

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    entrypoint: ""
    environment:
      MATRIX_URL: "http://tests"
      MATRIX_ID: "bot"
      MATRIX_PW: "pw"
    volumes:
      - ./:/app
