name: Lints

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - run: pipx install poetry
      - name: setup
        run: poetry install --with dev --no-interaction --no-ansi
      - run: poetry run flake8 .
      - run: poetry run black .
      - run: poetry run pydocstyle
      - run: poetry run safety check
      - run: poetry run poetry check
      - run: poetry run pyupgrade --py39-plus
